### ISSUE TITLE
Any idea on these errors?

### ISSUE THREAD

**Issue by sgaits** [DanMcInerney/fakeAP#5]
I am running this on Mint 17.1 (which may be the issue)..  However I thought I might ask and see if you knew what the issue might be.  I have run the script using sudo AND have run it while logged on as root, same error both times.  Wifijammer works great on Mint BTW!  Thank you very much for the awesome work!

[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "fakeAP.py", line 318, in <module>
    main(parse_args())
  File "fakeAP.py", line 297, in main
    mon_iface = start_monitor(ap_iface, channel)
  File "fakeAP.py", line 193, in start_monitor
    proc = Popen(['airmon-ng', 'start', ap_iface, channel], stdout=PIPE, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by DanMcInerney** [comment]
Seems you're missing aircrack.

Subprocess is the library that calls operating system commands and Popen is
a method of the subprocess library so an error in a line like, "proc =
Popen(['airmon-ng', 'start', ap_iface, channel]" means airmon-ng was not
found on your operating system.
