### ISSUE TITLE
Error parsing airmon's monitor interface

### ISSUE THREAD

**Issue by delamitry** [DanMcInerney/fakeAP#6]
I think the output scraping is broken when creating the monitored interface with airmon.  Could it be the new naming of monitored interfaces to wlan[x]mon instead of mon[x]?

My interface is wlan1
Monitored interface becomes wlan1mon

```
Traceback (most recent call last):
  File "fakeAP.py", line 318, in <module>
    main(parse_args())
  File "fakeAP.py", line 298, in main
    mon_mac1 = get_mon_mac(mon_iface)
  File "fakeAP.py", line 203, in get_mon_mac
    info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', mon_iface[:15]))
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by pawnsmaster** [comment]
same problem here

**Comment by DanMcInerney** [comment]
Yeah, I need to just rewrite this script. No timeline but it's on the agenda.

**Comment by DanMcInerney** [comment]
Working on the rewrite now using https://www.offensive-security.com/kali-linux/kali-linux-evil-wireless-access-point/

**Comment by DanMcInerney** [comment]
Can either of you run `asudo irmon-ng start <inferface>` then paste the output. Then can you run `sudo iwconfig` and paste the output? I'm having trouble recreating this issue.

**Comment by pawnsmaster** [comment]
1- sudo airmon-ng start wlan0
Output

    Found 4 processes that could cause trouble.
    If airodump-ng, aireplay-ng or airtun-ng stops working after
    a short period of time, you may want to kill (some of) them!
    PID Name
    1508 NetworkManager
    1619 wpa_supplicant
    1831 avahi-daemon
    1832 avahi-daemon

    PHY	Interface	Driver		Chipset

    phy0	wlan0mon	ath9k		Qualcomm Atheros AR9285 Wireless     Network Adapter (PCI-Express) (rev 01)

2- Sudo iwconfig

    eth0      no wireless extensions.

    wlan0mon  IEEE 802.11bgn  ESSID:"tedata"  
    Mode:Managed  Frequency:2.457 GHz  Access Point: xx:xx:xx:xx:xx:xx   
    Bit Rate=65 Mb/s   Tx-Power=15 dBm   
    Retry short limit:7   RTS thr:off   Fragment thr:off
    Encryption key:off
    Power Management:off
    Link Quality=50/70  Signal level=-60 dBm  
    Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
    Tx excessive retries:0  Invalid misc:36   Missed beacon:0

    lo        no wireless extensions.

even after killing the 4 processes it gives the same error

**Comment by DanMcInerney** [comment]
It was a change in the output of the updated aircrack suite. Fixed it and kept backwards compat.
